---
- name: "Facts:Netconf"
  hosts: all
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "username"
      prompt: "Enter username"
      default: "greg"
    - name: "password"
      prompt: "Enter password"
      private: yes

  tasks:
    - name: gathering info from device
      junos_get_facts:
          host={{ inventory_hostname }}
          user={{ username }}
          passwd={{ password }}
      register: junos
    - name: version
      debug: msg={{ junos.facts.version }}
    - name: serial-number
      debug: msg={{ junos.facts.serialnumber }}
